kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: quarkus-sa-template
objects:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: ${role_arn}
      name: ${service_account}
parameters:
  - name: role_arn
    description: "The AWS IAM Role ARN with dynamoDB access"
    required: true
  - name: service_account
    description: "The Openshift service account name"
    required: true
