AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template To Create a DynamoDB Table.'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'DynamoDB Parameters'
      Parameters:
      - ReadCapacityUnits
      - WriteCapacityUnits
      - BillingMode
      - SSEEncryptionKey
    - Label:
        default: 'AWS DynamoDb Tagging Parameters'
      Parameters:
      - costCenterParameter
      - iServerIDParameter
      - dataClassificationParameter
      - supportGroupParameter
      - assignmentGroupParameter
      - appCriticalityParameter
Parameters:
  # Dynamo parameters
  BillingMode:
    Description: Provisioned scaling mode
    Type: String
    Default: 'PAY_PER_REQUEST'
    AllowedValues:
      - 'PROVISIONED '
      - 'PAY_PER_REQUEST'      
  # SSEncryptionKey:
    # Description: KMS key to use for encryption of dynamo Db table. A CloudHSM back CMK must be used for resources with a restricted data classification, and a CMK must be used for resources with a confidential data classification, and a AWS KMS Key must be used for resources with a internal data classification, and a AWS KMS Key must be used for resources with a public data classification.
    # Type: String
  costCenterParameter:
    Description: The value for the costCenter tag.
    Type: String
    Default: TEST
  iServerIDParameter:
    Description: The value for the iServerID
    Type: String
    Default: TEST
  dataClassificationParameter:
    Description: The value for the dataClassificationParameter tag.
    Type: String
    AllowedValues: ['restricted','confidential','internal', 'public']
    Default: internal
  supportGroupParameter:
    Description: The value for the supportGroup.
    Type: String
    Default: TEST
  assignmentGroupParameter:
    Description: The value for the assignmentGroup
    Type: String
    Default: TEST
  appCriticalityParameter:
    Type: String
    Description: The value for the appCriticality tag
    AllowedValues: ['MV', 'MC', 'BC', 'BE', 'B']
    Default: B
  appenv:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Description: The name of the VPC Endpoint 
    Default: "/delta/account/environment"
  TableName:
    Type: String
    Description: Table to create in DynamoDb
    Default: Orders

  # Client Role parameters
  OidcIssuer:
    Description: SSM Parameter containing OpenID Connect issuer name for desired OpenShift cluster
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/delta/openshift/ccoe-dev-vstfb/oidc_issuer'
    AllowedPattern: '^/delta/openshift/[^/]+/oidc_issuer$'
  AppNamespace:
    Description: OpenShift namespace containing the app
    Type: String
    Default: 'quarkuscoffee'
  AppServiceAccount:
    Description: OpenShift service account used by the app
    Type: String
    Default: 'quarkuscoffee-counter-dynamodb-sa'
  AppRoleName:
    Description: AWS role name used by the app
    Type: String
    Default: 'delegate-admin-quarkuscoffee-counter-dynamodb-role'
  # DynamodbTableARN:
  #   Description: AWS dynamodb table used by the app
  #   Type: String
  #   Default: 'arn:aws:dynamodb:us-east-1:167772905579:table/Orders'

Conditions:
  istestEnv: !Equals [!Ref appenv, "sandbox"]
Resources:
  Orders:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: !Ref BillingMode
      AttributeDefinitions:
      - AttributeName: orderId
        AttributeType: S
      KeySchema:
      - AttributeName: orderId
        KeyType: HASH
      # SSESpecification:
        # KMSMasterKeyId: !Ref 'SSEncryptionKey'
        # SSEEnabled: true
        # SSEType: KMS
      TableName:
        Fn::If:
        - istestEnv
        - !Sub '${AWS::StackName}-${TableName}'
        - !Sub '${TableName}'
 
      Tags:
        - Key: assignmentGroup
          Value: !Ref assignmentGroupParameter
        - Key: costCenter
          Value: !Ref costCenterParameter
        - Key: dataClassification
          Value: !Ref dataClassificationParameter
        - Key: iServerID
          Value: !Ref iServerIDParameter
        - Key: supportGroup
          Value: !Ref supportGroupParameter
        - Key: appCriticalityTier
          Value: !Ref appCriticalityParameter
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES  
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref  AppRoleName
      Description: Permits quarkus app read and write access to DynamoDB table
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowOidcAssumeRole",
              "Effect": "Allow",
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Principal": {
                "Federated": [
                  "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OidcIssuer}"
                ]
              },
              "Condition": {
                "StringEquals": {
                  "${OidcIssuer}:aud": "sts.amazonaws.com",
                  "${OidcIssuer}:sub": "system:serviceaccount:${AppNamespace}:${AppServiceAccount}"
                }
              }
            }
          ]
        }
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/cft-developer-boundary-policy'
      Policies:
      - PolicyName: AppPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: PermitReadWriteOnlyAccessToApp
            Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:ConditionCheckItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
            Resource:
            - !GetAtt Orders.Arn

Outputs:
  DynamodbTableARN:
    Value: !GetAtt Orders.Arn
    Description: Name of the newly created DynamoDB table
    Export:
      Name: OrdersIacTestDynamodbTableARN
  AppRoleArn:
    Description: Test app role ARN
    Value: !GetAtt AppRole.Arn
  DynamodbStreamARN:
    Value: !GetAtt Orders.StreamArn 
    Description: Name of the newly created DynamoDB Stream 
    Export: 
      Name: DynamodbOrdersTableStreamARN