AWSTemplateFormatVersion: '2010-09-09'

Description: 'App role for read and write access to table in DynamoDB'

Parameters:

  OidcIssuer:
    Description: SSM Parameter containing OpenID Connect issuer name for desired OpenShift cluster
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/delta/openshift/ccoe-dev-vstfb/oidc_issuer'
    AllowedPattern: '^/delta/openshift/[^/]+/oidc_issuer$'

  AppNamespace:
    Description: OpenShift namespace containing the app
    Type: String
    Default: 'quarkuscoffee'

  AppServiceAccount:
    Description: OpenShift service account used by the app
    Type: String
    Default: 'quarkuscoffee-service-account'

  AppRoleName:
    Description: AWS role name used by the app
    Type: String
    Default: 'delegate-admin-quarkuscoffee-dynamodb-role'

  DynamodbTableARN:
    Description: AWS dynamodb table used by the app
    Type: String
    Default: 'arn:aws:dynamodb:us-east-1:167772905579:table/Orders'

Resources:

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref  AppRoleName
      Description: Permits quarkus app read and write access to DynamoDB table
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowOidcAssumeRole",
              "Effect": "Allow",
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Principal": {
                "Federated": [
                  "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OidcIssuer}"
                ]
              },
              "Condition": {
                "StringEquals": {
                  "${OidcIssuer}:aud": "sts.amazonaws.com",
                  "${OidcIssuer}:sub": "system:serviceaccount:${AppNamespace}:${AppServiceAccount}"
                }
              }
            }
          ]
        }
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/cft-developer-boundary-policy'
      Policies:
      - PolicyName: AppPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: PermitReadWriteOnlyAccessToApp
            Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:ConditionCheckItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
            Resource:
            - !Ref DynamodbTableARN

Outputs:

  AppRoleArn:
    Description: Test app role ARN
    Value: !GetAtt AppRole.Arn

