kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: counter-iac-aws-workspace
  namespace: quarkuscoffee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
